apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-attachments
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: vs-help-desk
    app.kubernetes.io/component: attachments
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
