// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VSHelpDesk.Infrastructure.Persistence;

#nullable disable

namespace VSHelpDesk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260807162503_AddPortalTicketRequests")]
    partial class AddPortalTicketRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.ApplicationParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ApplicationParameters", (string)null);
                });

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.ParameterChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ParameterKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParameterKey", "ChangedAt");

                    b.ToTable("ParameterChangeLogs", (string)null);
                });

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.PortalTicketRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_PortalTicketRequests_UserId_IdempotencyKey");

                    b.ToTable("PortalTicketRequests", (string)null);
                });

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.ProcessedEmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AcknowledgementAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AcknowledgementLastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcknowledgementLastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("AcknowledgementNextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AcknowledgementSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AcknowledgementStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Disposition")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceMessageId")
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ProcessedEmailMessages_IdempotencyKey");

                    b.HasIndex("TicketId");

                    b.HasIndex("AcknowledgementStatus", "AcknowledgementNextAttemptAt")
                        .HasDatabaseName("IX_ProcessedEmailMessages_AcknowledgementStatus_Acknowledgemen~");

                    b.ToTable("ProcessedEmailMessages", (string)null);
                });

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.SystemLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemLogs", (string)null);
                });

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("WaitingCustomerSince")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("CustomerEmail")
                        .HasDatabaseName("IX_Tickets_CustomerEmail_Trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CustomerEmail"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("CustomerEmail"), new[] { "gin_trgm_ops" });

                    b.HasIndex("CustomerName")
                        .HasDatabaseName("IX_Tickets_CustomerName_Trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CustomerName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("CustomerName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Subject")
                        .HasDatabaseName("IX_Tickets_Subject_Trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Subject"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Subject"), new[] { "gin_trgm_ops" });

                    b.HasIndex("LastActivityAt", "TicketNumber")
                        .IsDescending(true, false)
                        .HasDatabaseName("IX_Tickets_LastActivityAt_TicketNumber");

                    b.HasIndex("Status", "LastActivityAt", "TicketNumber")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("IX_Tickets_Status_LastActivityAt_TicketNumber");

                    b.HasIndex("Status", "WaitingCustomerSince", "Id")
                        .HasDatabaseName("IX_Tickets_Status_WaitingCustomerSince_Id");

                    b.HasIndex(new[] { "TicketNumber" }, "IX_Tickets_TicketNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "TicketNumber" }, "IX_Tickets_TicketNumber_Trgm")
                        .HasDatabaseName("IX_Tickets_TicketNumber_Trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "TicketNumber" }, "IX_Tickets_TicketNumber_Trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "TicketNumber" }, "IX_Tickets_TicketNumber_Trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.TicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("ScanVerdict")
                        .HasColumnType("integer");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<Guid>("TicketMessageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.HasIndex("TicketMessageId", "CreatedAt", "Id")
                        .HasDatabaseName("IX_TicketAttachments_TicketMessageId_CreatedAt_Id");

                    b.ToTable("TicketAttachments", (string)null);
                });

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.TicketMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("boolean");

                    b.Property<int>("SenderType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TicketId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_TicketMessages_TicketId_CreatedAt_Id");

                    b.ToTable("TicketMessages", (string)null);
                });

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.UserAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("AfterIsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("AfterRole")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool?>("BeforeIsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("BeforeRole")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("TargetUserId", "CreatedAt");

                    b.ToTable("UserAuditEvents", (string)null);
                });

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.PortalTicketRequest", b =>
                {
                    b.HasOne("VSHelpDesk.Domain.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSHelpDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.ProcessedEmailMessage", b =>
                {
                    b.HasOne("VSHelpDesk.Domain.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("VSHelpDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VSHelpDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.TicketAttachment", b =>
                {
                    b.HasOne("VSHelpDesk.Domain.Entities.TicketMessage", null)
                        .WithMany()
                        .HasForeignKey("TicketMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VSHelpDesk.Domain.Entities.TicketMessage", b =>
                {
                    b.HasOne("VSHelpDesk.Domain.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VSHelpDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
